name: Chainsaw Integration (CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -name: install dependencies
     run:  |
      wget -P chainsaw/ https://raw.githubusercontent.com/thestk/rtmidi/master/RtMidi.cpp
      wget -P chainsaw/ https://raw.githubusercontent.com/thestk/rtmidi/master/RtMidi.h
      sudo apt-get install libsfml-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
